### ISSUE TITLE
Order of arguments not preserved

### ISSUE THREAD

**Issue by rakeshr1** [Stanford-Mobisocial-IoT-Lab/sempre#20]
Sempre doesn't preserve the order of the arguments and so there is high probability of flipping arguments which can be disastrous sometimes like the following:

> change the filename from "XYZ" to "ABC"

where there is 50% probability the from and the to are exchanged

**Comment by gcampax** [comment]
I've been thinking that it might be useful to look into the dependency parse information from CoreNLP (and the dependencyParse feature in FeatureExtractor) for this, mostly because different arguments usually are under different prepositions in English

**Comment by gcampax** [comment]
It might also be worth looking at how Overnight deals with it, for cases like:
"articles whose name is foo whose author is bar"

lexical and phrase alignment don't help as long as you have
"articles whose name is bar whose author is foo"
in the dataset as well

-- are they going by type information only? (ie, foo must be a book name, bar must be a person name?)

**Comment by gcampax** [comment]
SEMPRE is obsolete.
