### ISSUE TITLE
"between Num1 and Num2" fails to parse

### ISSUE THREAD

**Issue by gcampax** [Stanford-Mobisocial-IoT-Lab/sempre#21]
Stupid CoreNLP is trying to be smart and parses the pattern as
"Num1-Num2"
Subsequently, NumberFn barfs on it

Example:
give me a random integer between 42 and 14 {
              Tokens: [give, me, a, random, integer, between, 42, and, 14]
              Lemmatized tokens: [give, I, a, random, integer, between, 42, and, 14]
              POS tags: [VB, PRP, DT, JJ, NN, IN, CD, CC, CD]
              NER tags: [O, O, O, O, O, O, NUMBER, NUMBER, NUMBER]
              NER values: [null, null, null, null, null, null, 42.0-14.0, 42.0-14.0, 42.0-14.0]
              targetValue: (string {\"query\":{\"name\":{\"id\":\"tt:builtin.get_random_between\"},\"args\":[{\"name\":{\"id\":\"tt:param.high\"},\"type\":\"Number\",\"value\":{\"value\":14},\"operator\":\"is\"},{\"name\":{\"id\":\"tt:param.low\"},\"type\":\"Number\",\"value\":{\"value\":42},\"operator\":\"is\"}]}})
              Dependency children: [[iobj->1, dobj->4], [], [], [], [det->2, amod->3, nmod:between->6, nmod:between->8], [], [case->5, cc->7, conj:and->8], [], []]
            }
WARNING: NumberFn: Cannot convert NerSpan "42.0-14.0" to a number

**Comment by rakeshr1** [comment]
Should we just change NumberFn to handle this case?

**Comment by gcampax** [comment]
Yeah but how?
It needs to paraphrase to
get random integer on builtin with low is 42 with high is 14
(which i know makes no sense but ignore that...)

so you need two separate NumberValues to be picked up by the ApplyFn -> AddOperatorFn -> AddValueFn chain

**Comment by gcampax** [comment]
We stopped using SUTime in the tokenizer.
