### ISSUE TITLE
Missing fig file

### ISSUE THREAD

**Issue by dniu16** [Stanford-Mobisocial-IoT-Lab/sempre#34]
Hi,
I'm trying to install TT-SEMPRE. When I ran the command "JAVAHOME= ant thingtalk", an error occurred as shown in the picture. 

<img width="1207" alt="screen shot 2017-06-09 at 5 46 10 pm" src="https://user-images.githubusercontent.com/7536839/26995594-95a83bba-4d3b-11e7-96b7-94be51044840.png">

I think the issue is that "fig.basic" is not present in the sempre-master file. Where can I get the file?
Thanks.
Jeff

**Comment by gcampax** [comment]
You must run "./pull-dependencies thingtalk" first

**Comment by dniu16** [comment]
I did run "./pull-dependencies thingtalk" first, the issue occurred when I ran "JAVAHOME= ant thingtalk"
