### ISSUE TITLE
Missing Fig File

### ISSUE THREAD

**Issue by dniu16** [Stanford-Mobisocial-IoT-Lab/sempre#35]
I did run "./pull-dependencies thingtalk" first, the issue occurred when I ran "JAVAHOME= ant thingtalk", as mentioned in the closed issue #34.

**Comment by gcampax** [comment]
Sorry, it might be the case that your JAVAHOME is incorrect then.
You should set it to wherever you installed java, like JAVAHOME=/usr/lib/jvm/java-1.8.0-openjdk

**Comment by gcampax** [comment]
I am assuming this was solved eventually.
